In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('data.csv')
data

,-log(C),Amax/Abs QPR,lambda dpr,Integral,Max Synthesis,lambda dpr synthesis,Cat
0,4.823909,1.506518,800,425.40,2.382,692,1
1,4.698970,1.569472,800,414.47,2.382,692,1
2,4.602060,1.634921,803,418.34,2.382,692,1
3,4.522879,1.671260,805,427.08,2.382,692,1
4,4.455932,1.694779,805,423.42,2.382,692,1
...,...,...,...,...,...,...,...
78,3.657577,1.915929,785,405.36,2.235,698,2
79,3.619789,1.954148,785,412.78,2.235,698,2
80,3.585027,1.929185,781,412.83,2.235,698,2
81,3.552842,1.902954,777,413.64,2.235,698,2
82,3.522879,1.882231,778,423.14,2.235,698,2